sobeys = [
"Beverages->Energy Drink",
"Beverages->Fresh Juice",
"Beverages->Juice->Allens",
"Beverages->Juice->Minute Maid&FiveAlive",
"Beverages->Juice->Oasis",
"Beverages->Juice->OceanSpray",
"Beverages->Juice->Other Juice",
"Beverages->Juice->V8&Motts",
"Beverages->Non-Dairy->Non-Daity Brinks",
"Beverages->Soft Drink->7up & Schweppes & MontainDew",
"Beverages->Soft Drink->CocaCola & Pepsi",
"Beverages->Soft Drink->Compliments",
"Beverages->Soft Drink->Crush & Cplus",
"Beverages->Soft Drink->Fruitopia & Fuze",
"Beverages->Soft Drink->Root Beer",
"Beverages->Soft Drink->Sprite & Canada Dry",
"Beverages->Soft Drink->Tea Beverage",
"Beverages->Water->Flavoured Water&Vitamin Water",
"Beverages->Water->Sparkling Water",
"Beverages->Water->Spring Water",
"Groceries->Canned Foods->Canned Beans & Peas",
"Groceries->Cereal & Breakfast->Cereal",
"Groceries->Cereal & Breakfast->Granola Bars & Tarts Bars",
"Groceries->Cereal & Breakfast->Oatmeal",
"Groceries->Coffee & Tea->Coffee",
"Groceries->Coffee & Tea->Hot Chocolate",
"Groceries->Coffee & Tea->Tea",
"Groceries->Condiments & Sauces->Honey & Syrup",
"Groceries->Condiments & Sauces->Jam",
"Groceries->Condiments & Sauces->Ketchup & Mustard",
"Groceries->Condiments & Sauces->Mayonnaise",
"Groceries->Condiments & Sauces->Salad Dressing",
"Groceries->Condiments & Sauces->Salt & Sugar",
"Groceries->Condiments & Sauces->Spreads",
"Groceries->Condiments & sauces->Pickles, Relish & Olives",
"Groceries->Dairy & Dairy Products->Kids Yogurt & Yogurt Beverage",
"Groceries->Dairy Products->Butter & Margarine",
"Groceries->Dairy Products->Cheese",
"Groceries->Dairy->Milk",
"Groceries->Dairy->Yogurt",
"Groceries->Dried Side Dishes",
"Groceries->Eggs",
"Groceries->Frozen Food->Frozen Vegetables",
"Groceries->Frozen Foods->Frozen Breakfast",
"Groceries->Frozen Foods->Frozen Fishes",
"Groceries->Frozen Foods->Frozen Fries & Onion Rings",
"Groceries->Frozen Foods->Frozen Juices and Fruits",
"Groceries->Frozen Foods->Frozen Meal",
"Groceries->Frozen Foods->Ice Cream",
"Groceries->Frozen Foods->Pizza Pops and Others",
"Groceries->Frozen Foods->Pizza",
"Groceries->Frozen Foods->Prepared and Frozen Meat",
"Groceries->Ham & Sausages",
"Groceries->Nuts & Seeds->Nuts",
"Groceries->Oil,Spices & Seasonning->Oil",
"Groceries->Pasta & Sauce->Pasta",
"Groceries->Soups & Cans->Canned Corn and Other Vegetables",
"Groceries->Soups & Cans->Canned Fruits",
"Groceries->Soups & Cans->Canned Meal",
"Groceries->Soups & Cans->Canned Meat",
"Groceries->Soups & Cans->Canned Soups",
"Groceries->Soups & Cans->Canned Tomatoes",
"Groceries->Soups & Cans->Dried Soups & Instant Noodles",
"Home & Lifestyle->Home Supplies->Bathroom & All Purpose Cleaning",
"Home & Lifestyle->Home Supplies->Bathroom Tissue",
"Home & Lifestyle->Home Supplies->Cleaning Supplies",
"Home & Lifestyle->Home Supplies->Facial Tissue",
"Home & Lifestyle->Home Supplies->Foil & Baking Pans",
"Home & Lifestyle->Home Supplies->Garbage Bags",
"Home & Lifestyle->Home Supplies->Laundry",
"Home & Lifestyle->Home Supplies->Paper Towel",
"Home & Lifestyle->Home Supplies->Plastic Wrap & Freezer Bags",
"Home & Lifestyle->Oral Care->Oral Rinse",
"Home & Lifestyle->Oral Care->Tooth Paste",
"Home & Lifestyle->Oral Care->Toothbrush",
"Home & Lifestyle->Personal Care->Antiperspirant & Deodorant",
"Home & Lifestyle->Personal Care->Body Wash",
"Home & Lifestyle->Personal Care->Facial Care & Body Lotion",
"Home & Lifestyle->Personal Care->Feminine Hygiene",
"Home & Lifestyle->Personal Care->Hair Enhancement",
"Home & Lifestyle->Personal Care->Hand Wash",
"Home & Lifestyle->Personal Care->Shampoo & Conditioner",
"Produce->Bakery->Breads",
"Produce->Bakery->Other Bakery Products",
"Snacks & Candies->Candies & Chocolates->Candies",
"Snacks & Candies->Candies & Chocolates->Chocolate Bars",
"Snacks & Candies->Candies & Chocolates->Chocolate Packs",
"Snacks & Candies->Candies & Chocolates->Gum",
"Snacks & Candies->Chips & Popcorn->Compliments & Sensations",
"Snacks & Candies->Chips & Popcorn->Dips",
"Snacks & Candies->Chips & Popcorn->Doritos",
"Snacks & Candies->Chips & Popcorn->Lays",
"Snacks & Candies->Chips & Popcorn->Miss Vickies",
"Snacks & Candies->Chips & Popcorn->Popchips & Rickworks",
"Snacks & Candies->Chips & Popcorn->Popcorn",
"Snacks & Candies->Chips & Popcorn->Pringles",
"Snacks & Candies->Chips & Popcorn->Ruffles",
"Snacks & Candies->Chips & Popcorn->SunChips & Cheetos & Fritos",
"Snacks & Candies->Chips & Popcorn->Tostitos",
"Snacks & Candies->Cookies & Biscuits->Biscuits",
"Snacks & Candies->Cookies & Biscuits->Cookies",
"Snacks & Candies->Cookies & Biscuits->Crackers",
"Snacks & Candies->Dried Fruit & Fruit Snacks->Fruit Cups",
"Snacks & Candies->Dried Fruit & Fruit Snacks->Fruit Snacks",
"Snacks & Candies->Pudding & Jello->Pudding",
]
bookstore = [
"Textbook->Anthropology->100",
"Textbook->Anthropology->200",
"Textbook->Anthropology->300",
"Textbook->Anthropology->400",
"Textbook->Arabic->100",
"Textbook->Arabic->200",
"Textbook->Archaeology->100",
"Textbook->Astronomy->100",
"Textbook->Biology->100",
"Textbook->Biology->200",
"Textbook->Biology->300",
"Textbook->Biology->400",
"Textbook->Biology->600",
"Textbook->Business->100",
"Textbook->Business->200",
"Textbook->Business->300",
"Textbook->Business->400",
"Textbook->Business->600",
"Textbook->Business->700",
"Textbook->Business->800",
"Textbook->Chemistry->100",
"Textbook->Chemistry->200",
"Textbook->Chemistry->300",
"Textbook->Chemistry->400",
"Textbook->Children's Education and Development->200",
"Textbook->Classical Studies->100",
"Textbook->Classical Studies->200",
"Textbook->Classical Studies->300",
"Textbook->Communication Studies->100",
"Textbook->Communication Studies->200",
"Textbook->Communication Studies->300",
"Textbook->Communication Studies->400",
"Textbook->Communication Studies->600",
"Textbook->Computer Science->100",
"Textbook->Computer Science->200",
"Textbook->Computer Science->300",
"Textbook->Computer Science->400",
"Textbook->Contemporary Studies->200",
"Textbook->Criminology->100",
"Textbook->Cultrral Analysis and Social Theory->600",
"Textbook->Cultural Studies->100",
"Textbook->Cultural Studies->200",
"Textbook->Economics->100",
"Textbook->Economics->200",
"Textbook->Economics->300",
"Textbook->Economics->400",
"Textbook->Economics->600",
"Textbook->Education->400",
"Textbook->English->100",
"Textbook->English->200",
"Textbook->English->300",
"Textbook->English->400",
"Textbook->English->600",
"Textbook->Environmental Studies->100",
"Textbook->Environmental Studies->200",
"Textbook->Environmental Studies->300",
"Textbook->Environmental Studies->400",
"Textbook->Faculty of Arts->100",
"Textbook->Film Studies->100",
"Textbook->Film Studies->200",
"Textbook->Film Studies->300",
"Textbook->Film Studies->400",
"Textbook->Film Studies->FS44",
"Textbook->French->100",
"Textbook->French->200",
"Textbook->French->300",
"Textbook->Geography->100",
"Textbook->Geography->200",
"Textbook->Geography->300",
"Textbook->Geography->400",
"Textbook->Geography->600",
"Textbook->German->100",
"Textbook->German->200",
"Textbook->Global Citizeship->100",
"Textbook->Global Citizeship->200",
"Textbook->Global Citizeship->300",
"Textbook->Global Governance->700",
"Textbook->Global Studies->100",
"Textbook->Global Studies->200",
"Textbook->Global Studies->300",
"Textbook->Global Studies->400",
"Textbook->Greek->100",
"Textbook->Greek->200",
"Textbook->Health Sciences->100",
"Textbook->Health Sciences->200",
"Textbook->Health Sciences->300",
"Textbook->Health Sciences->400",
"Textbook->History->100",
"Textbook->History->200",
"Textbook->History->300",
"Textbook->History->400",
"Textbook->History->600",
"Textbook->International Public Policy->600",
"Textbook->Italian->100",
"Textbook->Italian->200",
"Textbook->Italian->300",
"Textbook->Kinesiology and Physical Education->100",
"Textbook->Kinesiology and Physical Education->200",
"Textbook->Kinesiology and Physical Education->300",
"Textbook->Kinesiology and Physical Education->400",
"Textbook->Kinesiology and Physical Education->600",
"Textbook->Languages and Literature->200",
"Textbook->Latin->100",
"Textbook->Latin->200",
"Textbook->Mathematics->100",
"Textbook->Mathematics->200",
"Textbook->Mathematics->300",
"Textbook->Mathematics->400",
"Textbook->Mediterranean Studies->100",
"Textbook->Mediterranean Studies->200",
"Textbook->Mediterranean Studies->300",
"Textbook->Mediterranean Studies->400",
"Textbook->Music Studies->200",
"Textbook->Music->000",
"Textbook->Music->100",
"Textbook->Music->200",
"Textbook->Music->300",
"Textbook->Music->400",
"Textbook->Music->500",
"Textbook->Music->600",
"Textbook->Near Eastern Studies->100",
"Textbook->Near Eastern Studies->300",
"Textbook->North American Studies->100",
"Textbook->North American Studies->200",
"Textbook->North American Studies->300",
"Textbook->Philosophy->100",
"Textbook->Philosophy->200",
"Textbook->Philosophy->300",
"Textbook->Philosophy->400",
"Textbook->Philosophy->600",
"Textbook->Phychology->100",
"Textbook->Phychology->200",
"Textbook->Phychology->300",
"Textbook->Phychology->600",
"Textbook->Phychology->800",
"Textbook->Physics->100",
"Textbook->Physics->200",
"Textbook->Physics->300",
"Textbook->Physics->400",
"Textbook->Political Science->100",
"Textbook->Political Science->200",
"Textbook->Political Science->300",
"Textbook->Political Science->400",
"Textbook->Political Science->600",
"Textbook->Religion & Culture->100",
"Textbook->Religion & Culture->200",
"Textbook->Religion & Culture->300",
"Textbook->Religion & Culture->400",
"Textbook->Religion & Culture->600",
"Textbook->Social Welfare->100",
"Textbook->Social Work->500",
"Textbook->Social Work->600",
"Textbook->Social Work->700",
"Textbook->Sociology->100",
"Textbook->Sociology->200",
"Textbook->Sociology->300",
"Textbook->Sociology->400",
"Textbook->Sociology->600",
"Textbook->Spanish->100",
"Textbook->Spanish->200",
"Textbook->Spanish->300",
"Textbook->Spanish->400",
"Textbook->Theology->600",
"Textbook->Women and Gender Studies->100",
"Textbook->Women and Gender Studies->200",
"Textbook->Women and Gender Studies->300",
]

def cateForSobeys(cateList):
    category = {}
    for c in cateList:
      c = c.split('->')
      assert len(c) >= 2, 'incalid category format: %s' % c
      if c[0] not in category:
        category[c[0]]={}
      if c[1] not in category[c[0]]:
        category[c[0]][c[1]]=[]
      if len(c) == 3:
        category[c[0]][c[1]].append(c[2])
    return category


def getTextBookTopCate(c):
    if ord(c[0].upper()) <= ord('E'):
      return 'Department A-E'
    elif ord(c[0].upper()) <= ord('J'):
      return 'Department F-J'
    elif ord(c[0].upper()) <= ord('O'):
      return 'Department K-O'
    else:
      return 'Department P-Z'

def cateForBookStore(cateList):
    category = {}
    for c in cateList:
      c = c.split('->')
      assert len(c) >= 2, 'incalid category format: %s' % c
      if c[0] == 'Textbook':
        c[0] = getTextBookTopCate(c[1])
      if c[0] not in category:
        category[c[0]]={}
      if c[1] not in category[c[0]]:
        category[c[0]][c[1]]=[]
      if len(c) == 3:
        category[c[0]][c[1]].append(c[2])
    return category

category = {
    'sobeys' : cateForSobeys(sobeys),
    'bookstore' : cateForBookStore(bookstore),
}
